apiVersion: v1
kind: Namespace
metadata:
  name: infra
  labels:
    app.kubernetes.io/part-of: snackbar
    tier: infra
---
apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    app.kubernetes.io/part-of: snackbar
    tier: app
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  labels:
    app.kubernetes.io/part-of: snackbar
    tier: ingress